### ISSUE TITLE
Something wrong in building monotonic align module

### ISSUE THREAD

**Issue by blueblue-bubble** [naver-ai/facetts#1]
Hello,  when I run python setup.py build_ext --inplace to build monotonic align module, it will have an error: could not create 'model/monotonic_align/core.cpython-310-x86_64-linux-gnu.so': No such file or directory. I want to ask if you have met this problem and how to solve it.

**Comment by lee-jiyoung** [comment]
Hi,

Did you move to the directory first?
```
cd model/monotonic_align
```
And then you can install it, please. 
```
python setup.py build_ext --inplace
```

Let me know if you encounter any other error messages.

**Comment by Value-Jack** [comment]
i have the same promblem   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
error: could not create 'model/monotonic_align/core.cpython-38-x86_64-linux-gnu.so': No such file or directory
