### ISSUE TITLE
The inference result generates only a female voice regardless of the input image.

### ISSUE THREAD

**Issue by tskim9439** [naver-ai/facetts#2]
First of all, thank you for conducting the excellent research and for sharing the code.

I followed the instructions in the README, and successfully loaded the pretrained model.
To test the model, I have downloaded images of other people like Will Smith, changed the image file name to face2.png, but it seems to keep producing the same voice of a female.

Is there any additional work required to perform TTS conditioned on human face images?

**Comment by lee-jiyoung** [comment]
Hi,  sorry for the late response.

Did you use a face detector?
Since we use face images in LRS3 for training, the face in the image should be aligned like LRS3.
