### ISSUE TITLE
LRS3

### ISSUE THREAD

**Issue by gaoyiyao** [naver-ai/facetts#4]
求救，怎么下载lrs3数据集，我无法下载

**Comment by hesaijuan** [comment]
请问解决了嘛 可以分享下吗

**Comment by gaoyiyao** [comment]
> 请问解决了嘛 可以分享下吗

没有解决

**Comment by lee-jiyoung** [comment]
I don't understand what you said..😅 please ask me in English.

**Comment by gaoyiyao** [comment]
> 怎么下载lrs3数据集
For help, how to download the lrs 3 dataset, I can't download it

**Comment by lee-jiyoung** [comment]
Sorry, but please wait for the authors to re-share the dataset in [homepage](https://mmai.io/datasets/lip_reading/)
