### ISSUE TITLE
building monotonic align module

### ISSUE THREAD

**Issue by Value-Jack** [naver-ai/facetts#5]
i have the promblem when buiding the monotonic align module

/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
error: could not create 'model/monotonic_align/core.cpython-38-x86_64-linux-gnu.so': No such file or directory

**Comment by lee-jiyoung** [comment]
Have you installed Cython?

**Comment by Value-Jack** [comment]
yes,(facetts) zjli@tts-3090-2:~/work/tts/facetts/model/monotonic_align$ pip install cython
Requirement already satisfied: cython in /home/zjli/anaconda3/envs/facetts/lib/python3.8/site-packages (3.0.10)

this is my env CUDA Version: 12.0

**Comment by lee-jiyoung** [comment]
I recommend downgrading the cython package into cython==0.29.32

**Comment by Value-Jack** [comment]
/envs/facetts/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/home/zjli/anaconda3/envs/facetts/compiler_compat/ld: warning: /home/zjli/anaconda3/envs/facetts/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
error: could not create 'model/monotonic_align/core.cpython-38-x86_64-linux-gnu.so': No such file or directory

sorry still have this problem.  😭。 this is my cython type

(facetts) zjli@tts-3090-2:~/work/tts/facetts/model/monotonic_align$ pip show Cython
Name: Cython
Version: 0.29.32
Summary: The Cython compiler for writing C extensions for the Python language.
Home-page: http://cython.org/
Author: Robert Bradshaw, Stefan Behnel, Dag Seljebotn, Greg Ewing, et al.
Author-email: cython-devel@python.org
License: Apache
Location: /home/zjli/anaconda3/envs/facetts/lib/python3.8/site-packages
Requires: 
Required-by:

**Comment by Value-Jack** [comment]
about the environments,could you please share more details? the python version and the specific requirements

**Comment by Value-Jack** [comment]
maybe  some modules are too fresh

**Comment by lee-jiyoung** [comment]
I guess the build issue may be caused by a directory path or permission to create files in that folder. Because the error was issued with 'No such file or directory'.

**Comment by ShangkunTu** [comment]
> maybe some modules are too fresh

Hello！I’ve encountered the same issue as you. May I ask if you’ve found a solution, and if so, could you kindly share how you resolved it?

**Comment by ms-dot-k** [comment]
Just making dirs before running setup should be okay.

Instead of this:
```
cd model/monotonic_align; python setup.py build_ext --inplace; cd ../..
```
Try this:
```
cd model/monotonic_align; mkdir model; mkdir model/monotonic_align; python setup.py build_ext --inplace; cd ../..
```
